-- ============================================================
-- SETUP TABEL & KEAMANAN "santri_bulanan" DI SUPABASE
-- Jalankan ini di: Supabase Dashboard > SQL Editor
-- ============================================================
-- Ini adalah project Supabase BARU khusus untuk "Data Bulanan
-- Santri" (data pembayaran bulanan), TERPISAH dari project
-- Supabase lain yang mungkin sudah kamu pakai untuk aplikasi lain.
-- Jangan pakai URL/anon key project lama di sini, supaya data
-- kedua aplikasi tidak tercampur.

-- 1. Buat tabel utama.
--    - nis   : Nomor Induk Santri, dipakai untuk membedakan santri
--              dengan nama yang sama. Dibuat unik.
--    - aktif : status aktif santri (true = Aktif, false = Tidak Aktif).
--    - pembayaran : data status bayar per bulan per tahun, disimpan
--              sebagai JSON, contoh:
--              { "2024": [true,false,true,...  (12 nilai, Jan-Des)],
--                "2025": [false,false,...] }
create table if not exists public.santri_bulanan (
  id bigint generated by default as identity primary key,
  nis text not null unique,
  nama text not null,
  alamat text,
  aktif boolean not null default true,
  pembayaran jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- 2. Aktifkan RLS (Row Level Security) pada tabel.
--    Tanpa ini, siapa saja yang tahu URL project dan anon key (yang
--    memang publik, terlihat di kode HTML) bisa insert/update/delete
--    langsung ke tabel, walaupun mereka tidak pernah membuka
--    admin.html. Skrip ini mengunci itu di sisi server.
alter table public.santri_bulanan enable row level security;

-- 3. Hapus policy lama jika ada (aman dijalankan berulang kali).
drop policy if exists "Publik bisa membaca data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa menambah data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa mengubah data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa menghapus data santri bulanan" on public.santri_bulanan;

-- 4. Semua orang (termasuk yang belum login) boleh MEMBACA data.
--    -> ini yang dipakai oleh index.html (halaman publik).
create policy "Publik bisa membaca data santri bulanan"
on public.santri_bulanan for select
to anon, authenticated
using (true);

-- 5. Hanya pengguna yang SUDAH LOGIN (admin) yang boleh menambah data.
create policy "Admin bisa menambah data santri bulanan"
on public.santri_bulanan for insert
to authenticated
with check (true);

-- 6. Hanya pengguna yang sudah login yang boleh mengubah data
--    (termasuk menandai lunas/belum per bulan).
create policy "Admin bisa mengubah data santri bulanan"
on public.santri_bulanan for update
to authenticated
using (true)
with check (true);

-- 7. Hanya pengguna yang sudah login yang boleh menghapus data.
create policy "Admin bisa menghapus data santri bulanan"
on public.santri_bulanan for delete
to authenticated
using (true);

-- 8. Aktifkan realtime untuk tabel ini supaya perubahan (tambah/ubah/
--    hapus data, tandai lunas) langsung terlihat tanpa refresh.
--    (Aman dijalankan berulang; akan gagal diam-diam jika sudah aktif
--    di beberapa versi Supabase - itu tidak masalah.)
do $$
begin
  begin
    alter publication supabase_realtime add table public.santri_bulanan;
  exception when duplicate_object then
    null;
  end;
end $$;

-- ============================================================
-- LANGKAH TAMBAHAN (dilakukan lewat Dashboard, bukan SQL):
-- ============================================================
-- A. Matikan pendaftaran akun publik, supaya orang lain tidak bisa
--    membuat akun sendiri dan otomatis jadi "admin":
--    Authentication > Providers > Email > matikan "Allow new users
--    to sign up".
--
-- B. Buat akun admin secara manual:
--    Authentication > Users > Add user > isi email & password admin.
--    Gunakan email & password ini untuk login di admin/login.html.
--
-- C. (Opsional tapi disarankan) Jika ingin lebih dari satu admin
--    tanpa berbagi 1 akun, ulangi langkah B untuk tiap admin.
--
-- D. Salin "Project URL" dan "anon public" key dari
--    Project Settings > API, lalu tempelkan ke SUPABASE_URL dan
--    SUPABASE_ANON_KEY di index.html, admin/login.html, dan
--    admin/admin.html (3 tempat, harus sama persis).
-- ============================================================
