
create table if not exists public.santri_bulanan (
  id bigint generated by default as identity primary key,
  nis text not null unique,
  nama text not null,
  alamat text,
  tanggal_masuk date,
  tahun_keluar date,
  keterangan text,
  aktif boolean not null default true,
  pembayaran jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.santri_bulanan add column if not exists tanggal_masuk date;
alter table public.santri_bulanan add column if not exists tahun_keluar date;
alter table public.santri_bulanan add column if not exists keterangan text;

alter table public.santri_bulanan enable row level security;

drop policy if exists "Publik bisa membaca data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa menambah data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa mengubah data santri bulanan" on public.santri_bulanan;
drop policy if exists "Admin bisa menghapus data santri bulanan" on public.santri_bulanan;

create policy "Publik bisa membaca data santri bulanan"
on public.santri_bulanan for select
to anon, authenticated
using (true);

create policy "Admin bisa menambah data santri bulanan"
on public.santri_bulanan for insert
to authenticated
with check (true);

create policy "Admin bisa mengubah data santri bulanan"
on public.santri_bulanan for update
to authenticated
using (true)
with check (true);

create policy "Admin bisa menghapus data santri bulanan"
on public.santri_bulanan for delete
to authenticated
using (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.santri_bulanan;
  exception when duplicate_object then
    null;
  end;
end $$;

create table if not exists public.santri_bulanan_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  admin_email text,
  aksi text not null,
  santri_id bigint references public.santri_bulanan(id) on delete set null,
  nis text,
  nama text,
  detail jsonb not null default '{}'::jsonb
);

alter table public.santri_bulanan_log enable row level security;

drop policy if exists "Admin bisa membaca log aktivitas" on public.santri_bulanan_log;
drop policy if exists "Admin bisa menambah log aktivitas" on public.santri_bulanan_log;

create policy "Admin bisa membaca log aktivitas"
on public.santri_bulanan_log for select
to authenticated
using (true);

create policy "Admin bisa menambah log aktivitas"
on public.santri_bulanan_log for insert
to authenticated
with check (true);

create index if not exists santri_bulanan_log_created_at_idx
  on public.santri_bulanan_log (created_at desc);
create index if not exists santri_bulanan_log_santri_id_idx
  on public.santri_bulanan_log (santri_id);

